// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview Assesses the risk of ETA breaches, route deviations, and cold chain drifts for ongoing trips using AI.
 *
 * - aiPoweredTripRiskAssessment - A function that handles the trip risk assessment process.
 * - AiPoweredTripRiskAssessmentInput - The input type for the aiPoweredTripRiskAssessment function.
 * - AiPoweredTripRiskAssessmentOutput - The return type for the aiPoweredTripRiskAssessment function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AiPoweredTripRiskAssessmentInputSchema = z.object({
  tripId: z.string().describe('The ID of the trip to assess.'),
  plannedRoute: z.string().describe('The planned route of the trip.'),
  historicalData: z.string().describe('Historical data for similar trips.'),
  trafficConditions: z.string().describe('Current traffic conditions along the route.'),
  weatherConditions: z.string().describe('Current weather conditions along the route.'),
  cargoType: z.string().describe('The type of cargo being transported.'),
  tempSetpointC: z.number().optional().describe('The temperature setpoint for cold chain cargo in Celsius.'),
});
export type AiPoweredTripRiskAssessmentInput = z.infer<typeof AiPoweredTripRiskAssessmentInputSchema>;

const AiPoweredTripRiskAssessmentOutputSchema = z.object({
  riskEtaBreach: z.number().describe('The risk of an ETA breach, as a percentage.'),
  riskRouteDeviation: z.number().describe('The risk of a route deviation, as a percentage.'),
  riskColdChainDrift: z.number().describe('The risk of cold chain drift, as a percentage.'),
  recommendations: z.array(z.string()).describe('Proactive recommendations to address potential issues.'),
  reasoning: z.string().describe('Reasoning for the risk assessments.'),
});
export type AiPoweredTripRiskAssessmentOutput = z.infer<typeof AiPoweredTripRiskAssessmentOutputSchema>;

export async function aiPoweredTripRiskAssessment(input: AiPoweredTripRiskAssessmentInput): Promise<AiPoweredTripRiskAssessmentOutput> {
  return aiPoweredTripRiskAssessmentFlow(input);
}

const prompt = ai.definePrompt({
  name: 'aiPoweredTripRiskAssessmentPrompt',
  input: {schema: AiPoweredTripRiskAssessmentInputSchema},
  output: {schema: AiPoweredTripRiskAssessmentOutputSchema},
  prompt: `You are an AI assistant that assesses the risks associated with an ongoing trip and provides recommendations.

  Assess the risk of ETA breaches, route deviations, and cold chain drifts for the trip based on the provided information.
  Provide proactive recommendations to address potential issues and improve on-time delivery and cargo integrity.
  Present reasoning for the risk assessments.

  Trip ID: {{{tripId}}}
  Planned Route: {{{plannedRoute}}}
  Historical Data: {{{historicalData}}}
  Traffic Conditions: {{{trafficConditions}}}
  Weather Conditions: {{{weatherConditions}}}
  Cargo Type: {{{cargoType}}}
  Temperature Setpoint (Celsius): {{{tempSetpointC}}}

  Output:
  Risk of ETA Breach (%): {{riskEtaBreach}}
  Risk of Route Deviation (%): {{riskRouteDeviation}}
  Risk of Cold Chain Drift (%): {{riskColdChainDrift}}
  Recommendations: {{recommendations}}
  Reasoning: {{reasoning}}`,
});

const aiPoweredTripRiskAssessmentFlow = ai.defineFlow(
  {
    name: 'aiPoweredTripRiskAssessmentFlow',
    inputSchema: AiPoweredTripRiskAssessmentInputSchema,
    outputSchema: AiPoweredTripRiskAssessmentOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
