// This is an autogenerated file from Firebase Studio.
"use client";

import { useState, useEffect } from 'react';
import { User, onAuthStateChanged, getAuth, IdTokenResult } from 'firebase/auth';
import { useFirebaseApp } from '@/firebase';

type AuthState = {
  user: User | null;
  loading: boolean;
  claims: IdTokenResult['claims'] | null;
};

export function useUser() {
  const app = useFirebaseApp();
  const [authState, setAuthState] = useState<AuthState>({
    user: null,
    loading: true,
    claims: null,
  });

  useEffect(() => {
    // Only run on the client
    if (typeof window === 'undefined' || !app) {
      setAuthState({ user: null, loading: false, claims: null });
      return;
    }

    const auth = getAuth(app);
    const unsubscribe = onAuthStateChanged(auth, async (user) => {
      if (user) {
        const idTokenResult = await user.getIdTokenResult();
        setAuthState({ user, loading: false, claims: idTokenResult.claims });
      } else {
        setAuthState({ user: null, loading: false, claims: null });
      }
    });

    return () => unsubscribe();
  }, [app]);

  return authState;
}
