
// This is an autogenerated file from Firebase Studio.
"use client";

import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { getAuth, signInWithEmailAndPassword, GoogleAuthProvider, signInWithPopup, createUserWithEmailAndPassword } from "firebase/auth";
import { useRouter, useSearchParams } from "next/navigation";
import { useState, Suspense } from "react";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { AlertTriangle } from "lucide-react";
import Image from "next/image";

function LoginComponent() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const auth = getAuth();
  const [email, setEmail] = useState("admin@parnass.fr");
  const [password, setPassword] = useState("password");
  const [error, setError] = useState<string | null>(null);
  const accessError = searchParams.get('error') === 'access-denied';

  const handleLogin = async (e: React.FormEvent) => {
    e.preventDefault();
    setError(null);
    try {
      await signInWithEmailAndPassword(auth, email, password);
      router.push("/"); 
    } catch (err: any) {
       if (err.code === 'auth/invalid-credential' || err.code === 'auth/user-not-found') {
        // If user does not exist, create it.
        try {
          await createUserWithEmailAndPassword(auth, email, password);
          router.push("/");
        } catch (createErr: any) {
          setError(`Could not create user: ${createErr.message}`);
        }
      } else {
        setError(err.message);
      }
    }
  };

  const handleGoogleLogin = async () => {
    const provider = new GoogleAuthProvider();
    try {
      await signInWithPopup(auth, provider);
      router.push("/");
    } catch (err: any) {
      setError(err.message);
    }
  }

  return (
    <div className="relative flex min-h-screen items-center justify-center">
       <Image
        src="https://groupe-parnass.com/wp-content/uploads/2025/05/groupe-parnass-2.webp"
        alt="Background"
        fill
        style={{objectFit: 'cover'}}
        className="z-0"
        data-ai-hint="trucks highway"
      />
      <div className="absolute inset-0 bg-black/50 z-10" />
      <div className="z-20">
        <Card className="w-full max-w-sm">
          <CardHeader>
            <CardTitle className="text-2xl">Connexion</CardTitle>
            <CardDescription>
              Entrez vos identifiants pour vous connecter. Pour la démo, utilisez: admin@parnass.fr / password
            </CardDescription>
          </CardHeader>
          <CardContent className="grid gap-4">
            {accessError && (
               <Alert variant="destructive">
                <AlertTriangle className="h-4 w-4" />
                <AlertTitle>Accès refusé</AlertTitle>
                <AlertDescription>
                  Vous n'avez pas les permissions nécessaires pour accéder à cette application.
                </AlertDescription>
              </Alert>
            )}
            {error && (
              <Alert variant="destructive">
                  <AlertTriangle className="h-4 w-4" />
                  <AlertTitle>Erreur de connexion</AlertTitle>
                  <AlertDescription>{error}</AlertDescription>
              </Alert>
            )}
            <form onSubmit={handleLogin} className="grid gap-4">
              <div className="grid gap-2">
                <Label htmlFor="email">Email</Label>
                <Input
                  id="email"
                  type="email"
                  placeholder="m@example.com"
                  required
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                />
              </div>
              <div className="grid gap-2">
                <Label htmlFor="password">Mot de passe</Label>
                <Input 
                  id="password" 
                  type="password" 
                  required 
                  value={password}
                  onChange={(e) => setPassword(e.target.value)}
                />
              </div>
              <Button type="submit" className="w-full">
                Se connecter
              </Button>
            </form>
            <div className="relative">
              <div className="absolute inset-0 flex items-center">
                <span className="w-full border-t" />
              </div>
              <div className="relative flex justify-center text-xs uppercase">
                <span className="bg-card px-2 text-muted-foreground">
                  Ou continuer avec
                </span>
              </div>
            </div>
            <Button variant="outline" className="w-full" onClick={handleGoogleLogin}>
              Google
            </Button>
          </CardContent>
          <CardFooter>
            <p className="text-xs text-center text-muted-foreground w-full">
              Pas de compte? Le compte de démo sera créé pour vous.
            </p>
          </CardFooter>
        </Card>
      </div>
    </div>
  );
}


export default function LoginPage() {
  return (
    <Suspense fallback={<div>Loading...</div>}>
      <LoginComponent />
    </Suspense>
  )
}
