

// This is an autogenerated file from Firebase Studio.
"use client";

import { useUser } from "@/firebase/auth/use-user";
import { useRouter } from "next/navigation";
import { useEffect } from "react";
import { Home, Truck, Inbox, CircleHelp, LogOut, ArrowLeft } from "lucide-react";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { cn } from "@/lib/utils";
import { Button } from "@/components/ui/button";
import { getAuth, signOut } from "firebase/auth";
import { NotificationsSheet } from "@/components/driver/notifications-sheet";

// Mock user data for styling
const mockUser = {
  name: "Jean Dupont",
  role: "Chauffeur",
  imageUrl: "https://picsum.photos/seed/driver/100/100",
};

function DriverHeader() {
  const router = useRouter();
  const pathname = usePathname();

  const handleLogout = async () => {
    const auth = getAuth();
    await signOut(auth);
    router.push("/login");
  };

  const isSubPage = pathname.includes('/m/') && pathname.split('/m/')[1]?.includes('/');
  const isHomePage = pathname === '/m/home';
  
  let title = mockUser.name;
  if(pathname.startsWith('/m/trip-history/')) title = "Détails du Trajet";
  else if (pathname.startsWith('/m/new-ticket')) title = "Signaler Anomalie";
  else if (pathname.startsWith('/m/checklist')) title = "Checklist Départ";
  else if (pathname.startsWith('/m/inspection')) title = "Inspection Vidéo";
  else if (pathname.startsWith('/m/expenses')) title = "Note de Frais";
  else if (pathname.startsWith('/m/documents')) title = "Mes Documents";
  else if (pathname.startsWith('/m/profile')) title = "Mon Profil";
  else if (pathname.startsWith('/m/anomalies')) title = "Mes Anomalies";
  else if (pathname.startsWith('/m/maintenance')) title = "Maintenance";
  else if (pathname.startsWith('/m/inspections')) title = "Inspections";


  return (
    <header className="sticky top-0 z-50 flex items-center justify-between bg-background p-4 border-b">
      {isSubPage ? (
        <Button variant="ghost" size="icon" onClick={() => router.back()}>
          <ArrowLeft className="h-6 w-6" />
        </Button>
      ) : (
        <div className="flex items-center gap-3">
          <img src={mockUser.imageUrl} alt={mockUser.name} className="h-10 w-10 rounded-full" data-ai-hint="driver person" />
          <div>
            <h1 className="font-bold text-lg">{mockUser.name}</h1>
            <p className="text-sm text-muted-foreground">{mockUser.role}</p>
          </div>
        </div>
      )}

      {isSubPage && <h1 className="font-bold text-lg absolute left-1/2 -translate-x-1/2">{title}</h1>}

       <div className="flex items-center gap-2">
         {isHomePage && <Button variant="outline" size="sm" onClick={() => router.push('/dashboard')}>Vue Admin</Button> }
         <NotificationsSheet />
        <Button variant="ghost" size="icon" onClick={handleLogout}>
            <LogOut className="h-6 w-6" />
        </Button>
      </div>
    </header>
  );
}


function BottomNavBar() {
  const pathname = usePathname();
  const navItems = [
    { href: "/m/home", icon: Home, label: "Accueil" },
    { href: "/m/trip", icon: Truck, label: "Trajet" },
    { href: "/m/messages", icon: Inbox, label: "Messages" },
    { href: "/m/more", icon: CircleHelp, label: "Plus" },
  ];

  return (
    <nav className="fixed bottom-0 left-0 right-0 z-50 bg-background border-t">
      <div className="flex justify-around h-16">
        {navItems.map(({ href, icon: Icon, label }) => {
          const isActive = pathname.startsWith(href);
          return (
            <Link key={href} href={href} prefetch={false} className={cn("flex flex-col items-center justify-center w-full gap-1 text-xs", isActive ? "text-primary" : "text-muted-foreground")}>
              <Icon className="h-6 w-6" />
              <span>{label}</span>
            </Link>
          );
        })}
      </div>
    </nav>
  );
}


export default function DriverLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const { user, loading } = useUser();
  const router = useRouter();

  useEffect(() => {
    if (!loading && !user) {
      router.push("/login");
    }
  }, [user, loading, router]);

  if (loading) {
    // Show a loading screen or a blank page while checking auth
    return (
      <div className="flex h-screen w-full items-center justify-center">
        <p>Chargement...</p>
      </div>
    );
  }
  
  if (!user) {
      return null;
  }
  
  // Render the layout if the user is logged in, regardless of role.
  return (
    <div className="flex min-h-screen flex-col bg-muted/40">
      <DriverHeader />
      <main className="flex-1 overflow-y-auto p-4 pb-28">{children}</main>
      <BottomNavBar />
    </div>
  );
}
