// This is an autogenerated file from Firebase Studio.
import { FirebaseOptions } from "firebase/app";

// Your web app's Firebase configuration
// For Firebase JS SDK v7.20.0 and later, measurementId is optional
export const firebaseConfig: FirebaseOptions = {
    apiKey: "AIzaSyBKPVB8RMkp5kCLKnftidgMfQafGqrnmrU",
    authDomain: "studio-6127698026-9a847.firebaseapp.com",
    projectId: "studio-6127698026-9a847",
    storageBucket: "studio-6127698026-9a847.appspot.com",
    messagingSenderId: "324436887133",
    appId: "1:324436887133:web:582e61dcbfd978943cafb4",
    measurementId: "G-XXXXXXXXXX"
};
