// This is an autogenerated file from Firebase Studio.
"use client";

import { createContext, useContext } from "react";
import { FirebaseApp } from "firebase/app";
import { Auth } from "firebase/auth";
import { Firestore } from "firebase/firestore";

interface FirebaseContextType {
    app: FirebaseApp;
    auth: Auth;
    firestore: Firestore;
}

const FirebaseContext = createContext<FirebaseContextType | undefined>(undefined);

export function FirebaseProvider({ children, app, auth, firestore }: { children: React.ReactNode, app: FirebaseApp, auth: Auth, firestore: Firestore }) {
    return (
        <FirebaseContext.Provider value={{ app, auth, firestore }}>
            {children}
        </FirebaseContext.Provider>
    );
}

export const useFirebase = () => {
    const context = useContext(FirebaseContext);
    if (context === undefined) {
        throw new Error("useFirebase must be used within a FirebaseProvider");
    }
    return context;
};

export const useFirebaseApp = () => {
    return useFirebase().app;
}

export const useAuth = () => {
    return useFirebase().auth;
}

export const useFirestore = () => {
    return useFirebase().firestore;
}
