
// This is an autogenerated file from Firebase Studio.
import { config } from 'dotenv';
config();

import '@/ai/flows/ai-powered-trip-risk-assessment.ts';
import '@/ai/flows/predictive-maintenance.ts';
import '@/ai/flows/plan-trip-flow.ts';
import '@/ai/flows/cortex-recommendations-flow.ts';
import '@/ai/flows/kpi-root-cause-flow.ts';
import '@/ai/flows/tts-flow.ts';
import '@/ai/flows/suggest-replacement-flow.ts';
import '@/ai/flows/prospect-email-flow.ts';
